apiVersion: v2
appVersion: "v2.7.0"
description: Cloud Native storage for containers
name: ondat-operator
version: 0.5.9
keywords:
- storage
- block-storage
- volume
- operator
home: https://ondat.io
icon: https://docs.ondat.io/images/generic/Ondat_logo.svg
sources:
- https://github.com/ondat
maintainers:
- name: DavidMarchant
  email: david@ondat.io
- name:  mhmxs
  email: richard.kovacs@ondat.io
- name: aeroniero33
  email: angelos.perivolaropoulos@ondat.io
